done Hw15 calendar
hihoak/otus-course-hws pull request #16
Opened 2022-10-27 23:58 UTC by hihoak

## Домашнее задание №15 «Докеризация и интеграционное тестирование Календаря»

### Критерии оценки
- [ ] Проект полностью запускается и останавливается с помощью `make up` / `make down` - 3 балла
- [ ] Интеграционные тесты запускаются с помощью `make integration-tests`. Команда возвращает верный код ответа - 1 балл

Интеграционные тесты покрывают бизнес сценарии:
- [ ] добавление события и обработка бизнес ошибок - 2 балла
- [ ] получение листинга событий на день/неделю/месяц - 2 балла
- [ ] отправка уведомлений - 2 балла

#### Зачёт от 7 баллов

2022-10-27 23:59 UTC, hihoak commented
сделал только интеграционный тест на добавление ивента, сроки поджимают, так что пока что только так :(

2022-11-28 19:22 UTC, hihoak commented on hw12_13_14_15_calendar/build/migrations/Dockerfile
> +CMD goose -dir ${MIGRATIONS_FOLDER} up && sleep 120
вот тут я закостылил миграции, потому что по какой-то причине тесты фэйлились постоянно из-за того, что весь docker compose завершался после выполнения скрипта миграции и тесты банально не успевали выполниться, убил дофига времени на эту неприятную штуку. Можешь подсказать как сделать более правильно?

2022-11-30 19:01 UTC, Nikscorp requested changes
Артем, добрый вечер! Задание не доделано, нет необходимых интеграционных тестов, подробности в комментариях к PR.

2022-11-30 19:04 UTC, hihoak commented on hw12_13_14_15_calendar/build/calendar/Dockerfile
> +FROM ubuntu:18.04
alpine лично мне не очень нравится, там пусто и дебажить такие контейнеры грустно

2022-12-04 16:54 UTC, Nikscorp commented on hw12_13_14_15_calendar/cmd/sender/sender.go
> +	fmt.Println("creating directory in ", "/"+strings.Join(splitPath[:len(splitPath)-1], "/"))
NB: есть же логгер

2022-12-04 16:54 UTC, Nikscorp commented on hw12_13_14_15_calendar/internal/storage/sql/storage.go
> +	query := "UPDATE events "
NB: сложновато, лучше чтобы клиент всегда передавал все поля

2022-12-04 16:54 UTC, Nikscorp commented on hw12_13_14_15_calendar/build/migrations/Dockerfile
> +CMD goose -dir ${MIGRATIONS_FOLDER} up && sleep 120
миграции лучше запускать не через up, а через run отдельной командой

2022-12-04 16:59 UTC, Nikscorp approved these changes
Артем, добрый вечер!
Замечания исправлены, работа принята.

2023-08-10 09:05 UTC, merged